In [2]:
import torch.nn as nn
#model = nn.Linear(input_dim, output_dim)    #선형 회귀 모델

In [3]:
import torch.nn.functional as F
#cost = F.mse_loss(prediction, y_train)     #평균 제곱오차

#1. 단순 선형 회귀 구현하기

In [37]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [38]:
torch.manual_seed(1)

In [39]:
#데이터
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

In [40]:
# 모델을 선언 및 초기화 / 단순 선형 회귀이므로 input_dim = 1, output_dim = 1
model = nn.Linear(1,1)

In [41]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


첫번째 값 - W  
두번째 값 - b

In [42]:
#model.parameters를 사용하여 W와 b값 전달
optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)

In [43]:
nb_epochs = 2000
for epoch in range(nb_epochs + 1):

    #H(x)계산
    prediction = model(x_train)

    #cost계산
    cost = F.mse_loss(prediction,y_train)

    #cost로 H(x)개선
    #gradient를 0으로 초기화
    #optimizer.zero_grad()를 실행하므로서 미분을 통해 얻은 기울기를 0으로 초기화 / 기울기를 초기화해야만 새로운 가중치 편향에 대해서 새로운 기울기를 구할 수 있다
    optimizer.zero_grad()
    #비용 함수를 미분하여 gradient 계산
    cost.backward()
    #W와 b업데이트
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()))

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [44]:
new_var = torch.FloatTensor([4.0])
pred_y = model(new_var)
print('입력값 4의 예측값 : ',pred_y)

입력값 4의 예측값 :  tensor([7.9989], grad_fn=<AddBackward0>)


In [45]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


- H(x)식에 입력 x로부터 예측된 y를 얻는 것을 forward연산이라고 한다.  
- 학습 전, prediction = model(x_train)은 x_train으로부터 예측값을 리턴하므로 forward연산이다.
- 학습 후, pred_y = model(new_var)는 임의의 값 new_var로부터 예측값을 리턴하므로 forward연산이다.
- 학습 과정에서 비용 함수를 미분하여 기울기를 구하는 것을 backward 연산이라고 한다.
- cost.backward()는 비용 함수로부터 기울기를 구하라는 의미이며 backward 연산이다.

#2. 다중 선형 회귀구현하기

In [46]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [47]:
torch.manual_seed(1)

In [48]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [49]:
#다중 선형 회귀이므로 input_dim = 3 output_dim = 1
model = nn.Linear(3,1)

In [50]:
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]


In [51]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)    #SGD = Stochastic Gradient Descent 확률적 경사 하강법

In [52]:
nb_epochs = 2000
for epoch in range(nb_epochs + 1):

    #H(x)계산
    prediction = model(x_train)

    #cost계산
    cost = F.mse_loss(prediction,y_train)

    #cost로 H(x)개선
    #gradient를 0으로 초기화
    #optimizer.zero_grad()를 실행하므로서 미분을 통해 얻은 기울기를 0으로 초기화 / 기울기를 초기화해야만 새로운 가중치 편향에 대해서 새로운 기울기를 구할 수 있다
    optimizer.zero_grad()
    #비용 함수를 미분하여 gradient 계산
    cost.backward()
    #W와 b업데이트
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()))

Epoch    0/2000 Cost: 31667.597656
Epoch  100/2000 Cost: 0.225993
Epoch  200/2000 Cost: 0.223911
Epoch  300/2000 Cost: 0.221941
Epoch  400/2000 Cost: 0.220059
Epoch  500/2000 Cost: 0.218271
Epoch  600/2000 Cost: 0.216575
Epoch  700/2000 Cost: 0.214950
Epoch  800/2000 Cost: 0.213413
Epoch  900/2000 Cost: 0.211952
Epoch 1000/2000 Cost: 0.210560
Epoch 1100/2000 Cost: 0.209232
Epoch 1200/2000 Cost: 0.207967
Epoch 1300/2000 Cost: 0.206761
Epoch 1400/2000 Cost: 0.205619
Epoch 1500/2000 Cost: 0.204522
Epoch 1600/2000 Cost: 0.203484
Epoch 1700/2000 Cost: 0.202485
Epoch 1800/2000 Cost: 0.201542
Epoch 1900/2000 Cost: 0.200635
Epoch 2000/2000 Cost: 0.199769


In [53]:
new_var =  torch.FloatTensor([[73, 80, 75]]) 
pred_y = model(new_var) 
print("입력값 73, 80, 75일 때의 예측값 :", pred_y) 

입력값 73, 80, 75일 때의 예측값 : tensor([[151.2305]], grad_fn=<AddmmBackward0>)


In [54]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.9778, 0.4539, 0.5768]], requires_grad=True), Parameter containing:
tensor([0.2802], requires_grad=True)]
